### ISSUE TITLE
Request of support on openjdk 11

### ISSUE THREAD

**Issue by zhuyifengzju** [magmaOffenburg/RoboViz#107]
Hi,
I ran into a problem of starting roboviz when I am running the visualization on a machine with openjdk version 11.0.5. And the error message is as follows:

> Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

And I think the error is because of the different version of openjdk. Could you please also add support for openjdk version 11? Thanks!

**Comment by Seil0** [comment]
Hi,
That's not a problem of RoboViz. It is a bug in your openjdk. To my knowledge it has to do with glibc, which is used to compile openjdk. The only solution is to use openjdk 8 or [AdoptOpenJDK](https://adoptopenjdk.net/). Could you please also share some information about you OS?

**Comment by zhuyifengzju** [comment]
Thanks for the reply! I see. So my system is ubuntu 18.04, and I cannot really easily change the openjdk because the system is controlled by my department. If you could kindly point me to specific bugs that openjdk 11 has, I can send this information to my department and change the openjdk to a non-buggy version. Thanks!

**Comment by Seil0** [comment]
I can not provide any specific information on this bug, maybe you can find some information on that topic in the Ubuntu bug tracking system. Most People work around this behavior by downgrading to openjdk 8 or by using AdoptOpenJDK. AdoptOpenJDK can be found here: https://adoptopenjdk.net

**Comment by Seil0** [comment]
Since this is is a bug in some openjdk downstream versions. We can't do much in RoboViz.
