### ISSUE TITLE
Can't see remote server drawings

### ISSUE THREAD

**Issue by tirafesi** [magmaOffenburg/RoboViz#109]
Hello, I was wondering if you could help me.

I have a docker container running on a remote server. Inside this container, I run simspark and my agent. They are run on *localhost* on the default ports (i.e. monitor on localhost:3200, and agent sends drawing calls to localhost:32769). These ports are published so that they can be accessed from the outside of the container, like so:

```
0.0.0.0:8081->3200/tcp,
0.0.0.0:8082->32769/tcp
```

I edited the roboviz config file on my local computer to look like this:

```
Networking Settings:
Auto-Connect         : true
Auto-Connect Delay   : 1000
Server Hosts         : myserver
Server Port          : 8081
Drawing Port         : 8082
```

Now here is my problem: although roboviz shows the image properly, the drawings are not shown. How can I make roboviz also show the drawings?

**Comment by Gama11** [comment]
> agent sends drawing calls to localhost:32769

I guess it would have to use the IP of your local computer rather than localhost (which would be the remote in this case).

**Comment by tirafesi** [comment]
I thought of that, but why doesn't publishing the port work too?

The agent is drawing stuff to (container)localhost:32769, which is published to remote:8082, which roboviz connects to. So shouldn't roboviz see the messages sent with the drawing requests?

**Comment by Gama11** [comment]
Hm.. I just noticed:

>0.0.0.0:8082->32769/tcp

RoboViz uses UDP, not TCP.

**Comment by tirafesi** [comment]
Ah, so maybe that's why! I'll give it another try tomorrow and post the results here, thanks!

**Comment by tirafesi** [comment]
Nop, changing it to UDP did not work - still no drawings showing :(

Is there a way to start roboviz in a verbose mode or something along those lines, to see what is going wrong?

**Comment by Gama11** [comment]
No, but it's pretty easy to build from source / debug with breakpoints. Though I'm not sure that would help much, since you would likely just see no messages arriving...

**Comment by tirafesi** [comment]
Oh well, thanks for the help anyway! Feel free to close the issue.

**Comment by Gama11** [comment]
Ok, sorrry I couldn't be of more help. :) If you do get it working eventually, I'd love to hear what the problem was.
