### ISSUE TITLE
Unable to launch Roboviz with macOS Ventura

### ISSUE THREAD

**Issue by abuzar-rasool** [magmaOffenburg/RoboViz#132]
I was using Roboviz without any problems on macOS Monterey after the upgrade to macOS Ventura. The simulator window doesn't appear. There's no error in the terminal too.

**Comment by hannesbraun** [comment]
This is a known problem. I guess, it's probably due to some changes in version 3 of Metal. However, I'm not aware of any workarounds to make RoboViz run on macOS Ventura.
