### ISSUE TITLE
PlayerControls: playback speed textfield not selectable on Linux

### ISSUE THREAD

**Issue by Gama11** [magmaOffenburg/RoboViz#31]
Strangely enough, this is only an issue on linux and works fine on windows.

**Comment by Gama11** [comment]
Seems like this isn't specific to `JSpinner`, a regular text field has the same issue. Those are working on the configuration window though, so it must be something specific to `PlayerControls`...

**Comment by Gama11** [comment]
Seems like it's caused by some interaction with the roboviz main window actually, the textfields of the config window don't work either if open at the same time as the main window. This would also prevent #37 from working on linux.

**Comment by pmacalpine** [comment]
This is not an issue on mac either, just on linux.

**Comment by Seil0** [comment]
It seems like this issues occurs since the PlayerControls Frame does not have any focus.
