### ISSUE TITLE
Dialogs appear on other Desktop

### ISSUE THREAD

**Issue by klausdorer** [magmaOffenburg/RoboViz#54]
When I open e.g. the help screen it opens on another desktop so that I am not able to see it immediately. I am using a dual screen mode. RoboViz runs on my right screen, help window appears on the left screen of the next desktop to the right.
Ubuntu 12.04.

**Comment by Gama11** [comment]
I can't reproduce this issue on Windows 7 or my Ubuntu 14.04 virtual machine.

There's quite a bit of logic to make sure that RoboViz works nicely with multi-monitor setups, most of it in [SwingUtil](https://github.com/Gama11/RoboViz/blob/master/src/rv/util/swing/SwingUtil.java). Dialogs should appear on the monitor that the biggest percentage of the main window is located in. Specifically, they use `getCurrentScreenLocation()` via the call in `FramePanelBase`.

**Comment by mylamour** [comment]
it is also problem in ubuntu 14.04 and ubuntu 16.04 ,when you use two screen, it just can work in one side. roboviz will render again when it move to another screen.

**Comment by hannesbraun** [comment]
This probably can't be fixed from within RoboViz. It might rather be a problem with the desktop environment.
