### ISSUE TITLE
Logfile directory configuration option not being used

### ISSUE THREAD

**Issue by pmacalpine** [magmaOffenburg/RoboViz#61]
Logs are always saved to the "logfiles" directory and not what is specified in the configuration option.

**Comment by Gama11** [comment]
The logfile directory was only intended to be used for the file dialog in PlayerControls, not for recorded logfiles, so this isn't exactly a bug. I guess the config window presents this in a somewhat misleading way though.

I suppose it's convenient to use it for both?

**Comment by pmacalpine** [comment]
I see.  I was confused by this.  I think it might be nice to use it for both so as to prevent confusion but I don't think it's that big of an issue if not.  I doubt many people will ever record logs with roboviz as doing so directly with the server is a better option guaranteeing that you get every frame without losing any due to dropped monitor messages.  The real advantage to recording logs with roboviz is if drawings were recorded https://github.com/magmaOffenburg/RoboViz/issues/28.  Having drawings used for visual debugging information saved to logs would allow for nicely stepping through a log frame by frame to debug issues.  I was working on a prototype for https://github.com/magmaOffenburg/RoboViz/issues/28, but things started to get a bit complicated and I don't know if it will ever be finished.

**Comment by Gama11** [comment]
At what point did it get complicated? Also, what was your approach for recording drawings, did you save them in a separate or the same file?

**Comment by pmacalpine** [comment]
I was saving the draw commands in the same logfile file as a string representation of the byte [] send to roboviz, and had each draw command on its own line but with "draw::" appended to the front of the string.  To do this I added an interface for a DrawCommListener to DrawComm with a method to notify listeners when new draw commands were received, and then had ServerComm implement this interface where it was added as a listener to DrawComm so that it could write draw command messages out to the logfile.  This all worked well.  Unfortunately I accidentally blew away these changes due to my inexperience with git and not realizing that adding files while in one branch (but not committing them), and then reverting changes to these files while in another branch, would revert the file changes across all branches:P

The complicated part came in when I was looking at code in the log reader to traverse files and trying to figure out how to process the draw commands separately.  It might make sense and be easier to process draw commands if they were appended  to line entries in a logfile frame rather than putting them on separate lines.

**Comment by Gama11** [comment]
I think most people have had similar experiences when starting with git, me included. :)

Interesting... I was thinking drawings would have to be recorded to a separate file to make sure the recorded logfiles are still compatible with other logfile readers.
