### ISSUE TITLE
Some team colors not working and just showing up as black

### ISSUE THREAD

**Issue by pmacalpine** [magmaOffenburg/RoboViz#91]
I tried setting a team color to CC5500 (burnt orange) but it just shows up as black when teams load in roboviz.  I've seen this same behavior with some other colors too.  The commit that seems to have broken things is 4299274f4fb9d520db052d9b85ab7b2f5d1bf926.

**Comment by Gama11** [comment]
Integer divisions... -.-

Thanks for reporting!
